export type ShiftType = 'single' | 'dual';
export type ShiftTime = 'day' | 'night' | null;

export interface Branch {
  id: string;
  name: string;
  shift_type: ShiftType;
  expense_rate_target: number;
  created_at: string;
}

export interface Sale {
  id: string;
  branch_id: string;
  date: string;
  shift: ShiftTime;
  cash: number;
  mpesa: number;
  credit: number;
  total_sales: number; // Generated by Supabase
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface Expense {
  id: string;
  branch_id: string;
  date: string;
  amount: number;
  category: 'petty_cash' | 'hgp' | 'register';
  description: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface WasteEntry {
  id: string;
  branch_id: string;
  date: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface Credit {
  id: string;
  branch_id: string;
  date: string;
  type: 'paid' | 'staff';
  amount: number;
  description: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface WasteItem {
  id: string;
  waste_entry_id: string;
  item_name: string;
  quantity: number;
  unit_price: number;
  total_cost: number; // Generated by Supabase
}

export interface AuditLog {
  id: string;
  table_name: string;
  record_id: string;
  action: 'create' | 'update' | 'delete';
  old_data: any;
  new_data: any;
  performed_at: string;
}

// Supabase helper type for creating entries without generated IDs
export type CreateSale = Omit<Sale, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'total_sales'>;
export type CreateExpense = Omit<Expense, 'id' | 'created_at' | 'updated_at' | 'deleted_at'>;
export type CreateWasteEntry = Omit<WasteEntry, 'id' | 'created_at' | 'updated_at' | 'deleted_at'>;
export type CreateWasteItem = Omit<WasteItem, 'id' | 'total_cost'>;
export type CreateCredit = Omit<Credit, 'id' | 'created_at' | 'updated_at' | 'deleted_at'>;
